import ThemeProvider from '@/more/provider/ThemeProvider'
import AuthProvider from '@/more/provider/authentication/AuthProvider'
import UrlProvider from '@/more/context/serviceProvider'

import './globals.css'
import { Tajwal, Cairo, Noto } from '@/more/lib/fonts'
import { Toaster } from '@/components/ui/sonner'
import { getServerSession } from 'next-auth'
import { options } from '@/more/provider/authentication/options'
import { checkMails } from '@/app/_pagecomp/admin/mailsystem/db/inbox'
import NavBar from '@/components/menu/navbar/NavBar'
import Footer from '@/components/menu/footer/Footer'
import { getDepartmentsAndServicesFromDB } from './_pagecomp/home/bar/db'

// import Footer from '@/components/menu/Footer'
// export const dynamic = 'force-dynamic'
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app'
// }

export default async function RootLayout({ children }) {
  const session = await getServerSession(options)
  const newMails = await checkMails(session?.user?.email)

  return (
    <html lang='en' dir='rtl' suppressHydrationWarning>
      <body
        className={`${Tajwal.variable} ${Cairo.variable} ${Noto.variable}  container flex   w-full  flex-col   items-center justify-center  bg-muted/90 text-foreground  `}
      >
        <ThemeProvider
          attribute='class'
          defaultTheme='light'
          // enableSystem
          // defaultTheme='system'
          // enableSystem
          // disableTransitionOnChange
        >
          <UrlProvider>
            <AuthProvider session={session}>
              <NavBar session={session} newMails={newMails} />
              <main
                className='  mt-[60px]  flex   w-full grow flex-col items-center justify-center  text-foreground'
                id='mainlayout'
              >
                {children}
              </main>
              <Footer session={session} />
            </AuthProvider>
          </UrlProvider>
          <Toaster richColors position='top-center' closeButton />
        </ThemeProvider>
      </body>
    </html>
  )
}

// Warning: You're using `next/head` inside the `app` directory, please migrate to the Metadata API. See https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration#step-3-migrating-nexthead for more details.
